import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import anime from "animejs";
import Script from "next/script";

import { useState, useRef, useEffect } from "react";

const ticks = Array.from(Array(8));

export default function Home() {
  return (
    <div>
      <Script src="/anime.min.js"></Script>
      <Script src="/bg.js"></Script>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <canvas id="c">test</canvas>
    </div>
  );
}
